# Generated by Django 4.1.7 on 2023-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
